"""
emailer.py — Send the daily podcast via Gmail SMTP.

Requires:
  EMAIL_FROM       — your Gmail address
  EMAIL_TO         — recipient address (can be same as FROM)
  EMAIL_APP_PASSWORD — Gmail App Password (not your regular password)

The email contains:
  - Subject: 🎙️ Crypto Daily Brief — [Day, Month DD]
  - HTML body with the full text script
  - MP3 attachment
"""

import logging
import mimetypes
import os
import smtplib
from datetime import datetime
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import encoders
from pathlib import Path

logger = logging.getLogger(__name__)

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def _build_html_body(script: str, date: datetime) -> str:
    date_str = date.strftime("%A, %B %d, %Y")
    paragraphs = "".join(f"<p>{p.strip()}</p>" for p in script.split("\n\n") if p.strip())
    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {{ font-family: Georgia, serif; max-width: 680px; margin: 0 auto; color: #1a1a1a; }}
    h1 {{ font-size: 1.4em; border-bottom: 2px solid #f4a300; padding-bottom: 8px; }}
    .meta {{ color: #666; font-size: 0.9em; margin-bottom: 24px; }}
    p {{ line-height: 1.7; margin-bottom: 14px; }}
    .footer {{ margin-top: 32px; font-size: 0.8em; color: #999; border-top: 1px solid #eee; padding-top: 12px; }}
  </style>
</head>
<body>
  <h1>🎙️ Crypto Daily Brief</h1>
  <div class="meta">{date_str} · Sources: Messari · The Defiant · CoinTelegraph</div>
  <p><em>The MP3 podcast is attached. Full script below for reading.</em></p>
  <hr>
  {paragraphs}
  <div class="footer">Generated by Crypto Daily Brief · Automated daily digest</div>
</body>
</html>"""


def send(
    script: str,
    mp3_path: str | None,
    date: datetime | None = None,
    dry_run: bool = False,
) -> None:
    """
    Send the podcast email.

    Args:
        script:   Full podcast script text.
        mp3_path: Path to the MP3 file to attach (None = text only).
        date:     Date for subject line; defaults to today.
        dry_run:  If True, logs email content but does not send.
    """
    date = date or datetime.now()
    date_str = date.strftime("%A, %B %d")

    email_from = os.environ["EMAIL_FROM"]
    email_to = os.environ["EMAIL_TO"]
    app_password = os.environ["EMAIL_APP_PASSWORD"]

    subject = f"🎙️ Crypto Daily Brief — {date_str}"

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = email_from
    msg["To"] = email_to

    # HTML body
    html_body = _build_html_body(script, date)
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    # MP3 attachment
    if mp3_path and Path(mp3_path).exists():
        filename = Path(mp3_path).name
        with open(mp3_path, "rb") as f:
            part = MIMEBase("audio", "mpeg")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", "attachment", filename=filename)
        msg.attach(part)
        logger.info(f"Attaching MP3: {filename}")
    else:
        logger.warning("No MP3 to attach — sending text only")

    if dry_run:
        logger.info(f"[DRY RUN] Would send email to {email_to}")
        logger.info(f"  Subject: {subject}")
        logger.info(f"  Script length: {len(script)} chars")
        return

    logger.info(f"Sending email to {email_to}")
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(email_from, app_password)
        server.sendmail(email_from, email_to, msg.as_bytes())

    logger.info("Email sent successfully")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    sample_script = (
        "Welcome to Crypto Daily Brief. This is a test run.\n\n"
        "Everything looks great. The pipeline is working as expected.\n\n"
        "That's your Crypto Daily Brief for today. Stay sharp, stay informed — "
        "we'll see you tomorrow."
    )
    send(sample_script, mp3_path=None, dry_run=True)
